#!/bin/sh

bspc monitor HDMI-1 -d "1-www" "3-cli" "4-cli" 5 6 "7-daw" "8-game" 9 10
bspc monitor HDMI-2 -d "2-com"

CONF_DIR="$HOME/.config/bspwm"

# Load utility functions and config vars
. "$CONF_DIR/functions"
. "$CONF_DIR/variables"
. "$CONF_DIR/colors"

kill_running polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --log=error --reload all &
done


launch feh --bg-fill $HOME/Pics/Wallpapers-laptop/wallpaper-current.jpg &
launch sxhkd &
launch blueman-applet &
launch /usr/libexec/notification-daemon &
launch compton --vsync opengl
