- name: system configs
  file:
    src: /home/{{ user }}/Git/dots/{{ item.src }}
    dest: /etc/{{ item.dest }}
    state: link
    force: yes
  loop:
  - { src: lightdm/lightdm.conf, dest: lightdm/lightdm.conf }

- name: start services
  service:
    name: lightdm
    state: started
    enabled: yes

- name: set-default graphical.target
  command:
    cmd: systemctl set-default graphical.target
