#!/bin/sh
chassis=$(cat /sys/devices/virtual/dmi/id/chassis_type)
case $chassis in
	8 | 9 | 10 | 14 )
		#laptop
		bspc monitor eDP-1 -d "1-www" "2-com" "3-cli" "4-cli" 5 6 "7-daw" "8-game" 9 10
		;;
	3 | 4 | 6 | 7 )
		# desktop
		bspc monitor HDMI-1 -d "1-www" "3-cli" "4-cli" 5 6 "7-daw" "8-game" 9 10
		bspc monitor HDMI-2 -d "2-com"
		;;
esac

CONF_DIR="$HOME/.config/bspwm"
BSPWM_LOG_FILE="$CONF_DIR/logfile"

# Load utility functions and config vars
. "$CONF_DIR/functions"
. "$CONF_DIR/variables"
. "$CONF_DIR/colors"
. "$CONF_DIR/rules"

bspwmrc_logger "starting bspwm"

kill_running polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --log=error --reload all &
done


launch feh --bg-fill $HOME/Pics/Wallpapers-laptop/wallpaper-current.jpg &
launch sxhkd &
launch blueman-applet &
launch /usr/libexec/notification-daemon &
launch compton --vsync opengl
