- name: Initialize fedora netinstall
  hosts: localhost
  become: yes
  vars:
    user: eirik
  gather_facts: yes
  tasks:
    - package:
        name:
          - git
          - zsh
        state: present
  roles:
    - software

- name: configs
  hosts: localhost
  vars:
    user: eirik
    XDG_CONFIG_HOME: /home/{{ user }}/.config/
    type: desktop
  gather_facts: yes
  roles:
    - dots

- name: system configs
  hosts: localhost
  become: yes
  vars:
    user: eirik
  roles:
    - system
