# Path to your oh-my-zsh installation.
export ZSH=/home/eirik/.oh-my-zsh

# Setting fd as the default source for fzf to respect .gitignore
FZF_DEFAULT_COMMAND="fd --type f"
FZF_CTRL_T_COMMAND="fd --type f"
FZF_ALT_C_COMMAND="fd --type d"

# Theme, one for remote
if [[ -n $SSH_CLIENT ]]
then
	ZSH_THEME="gentoo"
else
	ZSH_THEME="af-magic"
fi


COMPLETION_WAITING_DOTS="true"

# Plugins
plugins=(git)

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt:$HOME/.cargo/bin:/opt/anaconda3/bin:$HOME/.config/scripts:/opt/blender-current:$HOME/.local/bin"
export GOPATH="$HOME/.local/go"
export PATH="$PATH:$GOPATH/bin"
export EDITOR=emacsclient


source $ZSH/oh-my-zsh.sh

# Ranger levels check
rr() {
	if [ -z "$RANGER_LEVEL" ]
	then
		ranger
	else
		exit
	fi
}

#Alias for the LS comand
alias ll='ls -hAl --group-directories-first'
alias l='ls -GghB --group-directories-first'
alias lc='ls -gGht'
alias llc='ls -hAlt'

alias dirs='dirs -v'

# Alias for Git
alias g='git'
alias gc='git commit'
alias gs='git status'
alias gp='git push'

# General alias
alias c='xclip -sel clip'
alias p='xclip -sel clip -o'

# Open file
open_file(){
	xdg-open $1 &
}
alias open="open_file"

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
	source /etc/profile.d/vte.sh
fi

alias vim=nvim
alias :q=exit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ -s "$HOME/.xmake/profile" ]] && source "$HOME/.xmake/profile" # load xmake profile

source /home/eirik/.config/broot/launcher/bash/br

ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
