# Path to your oh-my-zsh installation.
  export ZSH=/home/eirik/.oh-my-zsh

# Theme, one for remote
if [[ -n $SSH_CLIENT ]]
then
	ZSH_THEME="gentoo"
else
	ZSH_THEME="af-magic"
fi


COMPLETION_WAITING_DOTS="true"

# Plugins
plugins=(git)
plugins=(zsh-autosuggestions)


export PATH="/home/eirik/Bin:/home/eirik/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export EDITOR=/usr/bin/nvim
export XDG_CONFIG_HOME=$HOME/.config

source $ZSH/oh-my-zsh.sh

# Ranger levels check	     
rr() {			     
    if [ -z "$RANGER_LEVEL" ]
	then		     
	    ranger	     
	else		     
	    exit	     
    fi			     
}			     

#Alias for the LS comand    
alias ll='ls -hAl --group-directories-first'	
alias l='ls -GghB --group-directories-first'	
alias lc='ls -gGht'				
alias llc='ls -hAlt'  		

alias dirs='dirs -v'

#Alias for SSH
alias chat='ssh kad_wee%r -t TERM=rxvt-unicode && tmux a -d -t twee'
alias hv1='ssh kad_hv1%r'

# Alias for Git
alias g='git'
alias gc='git commit'
alias gs='git status'
alias gp='git push'

# General alias
alias c='xclip -sel clip'

# Custom cd
customCD(){
    cd $1;
    ls;
}
alias cd="customCD"

# keybinds
# up
function up_widget() {
	BUFFER="cd .."
	zle accept-line
}
zle -N up_widget
bindkey "^k" up_widget

# home
function goto_home() {
	BUFFER="cd ~/"$BUFFER
	zle end-of-line
	zle accept-line
}
zle -N goto_home
bindkey "^h" goto_home



if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

alias :q=exit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
